# Generated by Django 5.0.6 on 2024-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publicatin_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
