# Generated by Django 5.0.6 on 2024-08-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_publicatin_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicatin_year',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='titel',
            new_name='title',
        ),
    ]
